package render

import engine.EngineAdapter
import engine.EngineTestSupport
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestInstance
import rpc.Density
import rpc.DevicePreset
import rpc.DocKind
import rpc.Orientation
import rpc.PreviewConfig
import rpc.RenderRequest
import rpc.RenderRouting
import rpc.RenderStatus
import rpc.SizeBucket
import java.io.File
import java.nio.file.Files
import javax.imageio.ImageIO

/**
 * T89 (LAY-08 AC1-AC3) — the previewed root's own `layout_width`/`layout_height`/margins/gravity
 * must be honored instead of the pre-fix full-bleed defect (DF-4). Driven through [RenderRouting]
 * over new framework-gallery `rootparams_*` fixtures (§FR-1 style), with pixel-level assertions:
 * corpus goldens are generated by this same engine, so only absolute pixel checks (uncovered-canvas
 * color, inset positions) can discriminate the fix from the defect.
 *
 * LAY-08 AC4 (amended 2026-07-28, mid-execution correction): canvas not covered by the root shows
 * the resolved theme's `windowBackground`/`colorBackground`, not transparency — engine-verified that
 * `decor=false` only suppresses system chrome (`SessionParams.setForceNoDecor()`), not background
 * painting. `THEME_BG` below is `android:Theme.Material.NoActionBar`'s resolved
 * `background_material_dark` (`#FF303030`), confirmed empirically by swapping in a light theme and
 * observing the exact `background_material_light` (`#FFFAFAFA`) instead.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class RootLayoutParamsTest {

  private val pkg = "com.inflate.preview"
  private lateinit var res: File
  private lateinit var routing: RenderRouting
  private var idSeq = 0

  // android:Theme.Material.NoActionBar's resolved background_material_dark.
  private val THEME_BG = 0xFF303030.toInt()

  // The rootparams_* fixtures' own opaque root background (#FF224488) — distinct from THEME_BG so
  // "painted by the root" vs. "shows the theme background" are unambiguous in pixel assertions.
  private val ROOT_BG = 0xFF224488.toInt()

  @BeforeAll
  fun setUp() {
    val src = File(EngineTestSupport.fixturesRoot(), "galleries/framework")
    require(src.isDirectory) { "framework gallery fixtures missing at $src" }
    val proj = Files.createTempDirectory("inflate-rootparams-gallery").toFile()
    src.copyRecursively(proj, overwrite = true)
    res = File(proj, "res")
    val overlayBaseDir = Files.createTempDirectory("inflate-rootparams-overlay").toFile()
    val outputDir = Files.createTempDirectory("inflate-rootparams-out").toFile()

    val adapter = EngineAdapter(
      runtimeRoot = EngineTestSupport.runtimeRoot(),
      resourcesRoot = EngineTestSupport.resourcesRoot(),
    )
    adapter.initBridgeOnce(
      EngineAdapter.previewEnvironment(appTestDir = proj, roots = listOf(res), packageName = pkg),
    )
    routing = RenderRouting(adapter, outputDir = outputDir, overlayBaseDir = overlayBaseDir)
  }

  // mdpi keeps 1dp == 1px, so pixel coordinates below can be reasoned about in dp directly.
  private fun config(): PreviewConfig = PreviewConfig(
    themeName = "android:Theme.Material.NoActionBar",
    isProjectTheme = false,
    night = false,
    device = DevicePreset("test", "Test", 200, 300, "mdpi", SizeBucket.normal),
    orientation = Orientation.portrait,
    density = Density.mdpi,
    pixelScale = 1,
    drawable = null,
  )

  private fun request(docName: String): RenderRequest = RenderRequest(
    id = ++idSeq,
    docPath = File(res, "layout/$docName.xml").absolutePath,
    docKind = DocKind.layout,
    inlineContent = null,
    roots = listOf(res.absolutePath),
    packageName = pkg,
    config = config(),
    timeoutMs = 15000,
  )

  private fun argbAt(pngPath: String, x: Int, y: Int): Int {
    val img = ImageIO.read(File(pngPath))
    return img.getRGB(x, y)
  }

  @Test
  fun `wrap_content root paints only its wrapped band, top-start anchored (LAY-08 AC1, AC3)`() {
    val r = routing.render(request("rootparams_wrap"))
    assertEquals(RenderStatus.ok, r.status, "should render; error=${r.error?.message}")
    val png = r.pngPath!!
    assertEquals(ROOT_BG, argbAt(png, 5, 5), "top-start corner of the 100dp child must be the root's own background")
    assertEquals(ROOT_BG, argbAt(png, 100, 50), "inside the wrapped 100dp band must be the root's own background")
    assertEquals(
      THEME_BG,
      argbAt(png, 100, 150),
      "the device vertical center is below the wrapped bounds — must show the theme background, not the root's",
    )
  }

  @Test
  fun `root margins inset the wrapped area, density-scaled (LAY-08 AC2)`() {
    val r = routing.render(request("rootparams_margins"))
    assertEquals(RenderStatus.ok, r.status, "should render; error=${r.error?.message}")
    val png = r.pngPath!!
    assertEquals(THEME_BG, argbAt(png, 8, 50), "inside the 16dp left margin band must show the theme background")
    assertEquals(THEME_BG, argbAt(png, 190, 50), "inside the 16dp right margin band must show the theme background")
    assertEquals(THEME_BG, argbAt(png, 100, 5), "inside the 16dp top margin band must show the theme background")
    assertEquals(ROOT_BG, argbAt(png, 20, 20), "just past the density-scaled inset must be the root's own background")
  }

  @Test
  fun `match_parent root still fills the entire canvas (LAY-08 AC1 regression guard)`() {
    val r = routing.render(request("rootparams_match"))
    assertEquals(RenderStatus.ok, r.status, "should render; error=${r.error?.message}")
    val png = r.pngPath!!
    assertEquals(ROOT_BG, argbAt(png, 2, 2), "top-left corner must stay painted (full-bleed unchanged)")
    assertEquals(ROOT_BG, argbAt(png, 197, 2), "top-right corner must stay painted")
    assertEquals(ROOT_BG, argbAt(png, 2, 297), "bottom-left corner must stay painted")
    assertEquals(ROOT_BG, argbAt(png, 197, 297), "bottom-right corner must stay painted")
  }

  @Test
  fun `root layout_gravity positions a fixed-size root within the canvas (LAY-08 AC3)`() {
    val r = routing.render(request("rootparams_gravity"))
    assertEquals(RenderStatus.ok, r.status, "should render; error=${r.error?.message}")
    val png = r.pngPath!!
    assertEquals(
      THEME_BG,
      argbAt(png, 10, 10),
      "top-left region must show the theme background — root is gravity bottom|end",
    )
    assertEquals(ROOT_BG, argbAt(png, 150, 250), "bottom-right 100dp region must be the root's own background")
  }
}
